
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Business Objects.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\CarSound.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\ComputerSpeech.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Controls.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Domain Models.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Exceptions.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\HelperClasses.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Log.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Logger.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\MockObjects.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\MusicPlayer.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\ParallelPortDataParser.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\ParallelPortReader.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\PortDataParser.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Presentation Framework.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceActionSound.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceControlService.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceDataService.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceOptionsService.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceRecovery.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceSound.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\RaceSoundService.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Serialization.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\SerialPortReader.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Tracing.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Windows Forms Model.dll"
C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\NGen.exe install "..\Windows Forms View.dll"
